Fix compilation and pack assets
domis4/vita-libvita2d-game pull request #3
Opened 2023-12-06 09:31 UTC by dleovl

I've really been touched by this, this is a really beautiful project. It's an honest shame it's been abandoned, I feel like it could've been something nice. I fixed compiling (you may need to go into VitaSDK and fix references to <stdlib.h> in C++ headers to the direct path of stdlib.h in VitaSDK (that's why game-module.h and sprite.h have an explicit path, please do change it to your SDK path)) and replaced the outdated Makefile with a current CMakeLists.txt which should perform the same if not better, packing in the assets too since it was a pain in the ass to figure out the app was crashing because the assets were literally missing from my Vita. I saw you here, https://www.youtube.com/watch?v=XAEsMtHFTwc, and then here, https://www.youtube.com/watch?v=3YxhuEGMrEI, just amazing. Still got the Mio brick wall?

VPK: [domis4cpp.vpk.zip](https://github.com/domis4/vita-libvita2d-game/files/13579034/domis4cpp.vpk.zip)

2023-12-06 09:53 UTC, domis4 commented
Thanks, unfortunatelly i dont have a vita anymore. I removed the mio brick wall back then from the repo, due to copyright concerns and i think its lost since then.

Thank you for your effort, happy if someone make use of this :) i will review the changes

2023-12-06 10:00 UTC, domis4 requested changes
Great Work and thank you very much!

i dont understand why the full stdlib.h needs to be hardcoded.

2023-12-06 10:00 UTC, domis4 commented on CMakeLists.txt
> +  app/src/main.cpp
the old makefile would use find instead of hardcoded list of source files. Would you be able to do the same? im not familiar with cmake

https://github.com/domis4/vita-libvita2d-game/pull/3/commits/dd0ec775b25b316287edb65ed5ded07506f94584#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L5

2023-12-06 10:00 UTC, domis4 commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 2.8)
great work on converting the old makefile this into a more modern format

2023-12-06 10:00 UTC, domis4 commented on app/src/game/sprite/sprite.h
> +#include "/usr/local/vitasdk/arm-vita-eabi/include/c++/10.3.0/stdlib.h"
i'm very rusty in c++ and vitasdk, but this seems very inflexibel, even being dependent of the users OS. Why wouldn't vitasdk be able to import sdlib.h itself?

2023-12-06 10:01 UTC, dleovl commented
> Thanks, unfortunatelly i dont have a vita anymore. I removed the mio brick wall back then from the repo, due to copyright concerns and i think its lost since then.
> 
> Thank you for your effort, happy if someone make use of this :) i will review the changes

So glad to see you see this. I've been eyeing it for a couple weeks ever since seeing your YouTube video and decided I wanted it myself. Mio is understandable, just thought it was cute lol. I really suggest Vita3K if you ever do touch Vita development again, it's really come a long way (and so has the entire modding scene!).

The only thing that may be offputting is those /usr/local/vitasdk/ explicit paths. Would be normal on a Linux install apart from having to manually modify any files in the errors during compilation to change `<stdlib.h>` to the actual path of stdlib.h (which is a problem for C++ projects in general, not exclusive to yours), but I'm not sure how to fix it myself, even Makefile couldn't fix it. Everything is just bringing it up to date with modern VitaSDK without touching your actual code.

2023-12-06 10:04 UTC, imnltsa commented on app/src/game/sprite/sprite.h
> +#include "/usr/local/vitasdk/arm-vita-eabi/include/c++/10.3.0/stdlib.h"
> i'm very rusty in c++ and vitasdk, but this seems very inflexibel, even being dependent of the users OS. Why wouldn't vitasdk be able to import sdlib.h itself?

I've left a comment here: https://github.com/domis4/vita-libvita2d-game/pull/3#issuecomment-1842559597

It's an existing issue with VitaSDK and C++. Even if you tried to compile your 6 year old version, stdlib.h would just say it doesn't exist despite being in the includes. I'm as clueless as you are, but this is the only thing that I myself aren't comfortable with in this PR either :)

This is the default location for Linux, likely WSL2 too. It will require manual editing along with editing VitaSDK itself. It's out of my hands, I believe.

2023-12-06 10:07 UTC, imnltsa commented on CMakeLists.txt
> +  app/src/main.cpp
> the old makefile would use find instead of hardcoded list of source files. Would you be able to do the same? im not familiar with cmake
> 
> [dd0ec77#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L5](https://github.com/domis4/vita-libvita2d-game/commit/dd0ec775b25b316287edb65ed5ded07506f94584#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L5)

Either the directories or the files themselves will have to be coded into CMake, and since each cpp file is in its own subdirectory, it seemingly leaves no choice but to hardcode it. CMake pretty much compiles into a Makefile anyway though, so it's probably possible, I will definitely look into it.

2023-12-06 11:19 UTC, closed without merging

2023-12-06 11:19 UTC, dleovl commented
Sorry for bothering you. I was able to officially automatically add every .cpp file into the eboot.bin, but whatever you may try to do to add all of the assets, it inevitably ends up corrupted on the Vita. I still don't know how to fix the stdlib either, its behavior is entirely unintentional and shouldn't at all be happening. May I wish you the best.

2023-12-06 23:21 UTC, dleovl commented
For future reference, I believe you are able to do an /app/src/*.cpp GLOB_RECURSE for adding executables, but VitaSDK's `vita_create_vpk` requires you to use the FILE parameter to add files. You can't add a folder I believe; you need to add every asset manually and where they should be in the VPK (It LOOKS fine when you do `FILE assets/ assets/` on Linux,  even when unzipping, but as soon as you send it over to your Vita it can't install it in VitaShell, because what you just did is add every file in the assets folder to a file named assets making multiple copies of the same file which isn't at all supported and shouldn't even be like this in the first place, pretty much breaking the VPK and making it uninstallable). If anyone knows how to fix stdlib.h too, please do let me know. It happens on a clean install of VitaSDK on Linux where it just doesn't pick up stdlib.h for C++ projects *ONLY* despite it literally being in `${VITASDK}/arm-vita-eabi/include/c++/10.3.0`. You need to manually change any C++ file to hardcode the paths of the real files (for example `${VITASDK}/arm-vita-eabi/include/c++/10.3.0/cmath` line 45 needs to change to `#include_next "/usr/local/vitasdk/arm-vita-eabi/include/c++/10.3.0/math.h"`, or a similar directory structure, for math.h to be seen) even though CMAKE_CXX_FLAGS is set to `-I${VITASDK}/arm-vita-eabi/include/c++/10.3.0` and include_directories has `${VITASDK}/arm-vita-eabi/include/c++/10.3.0`. This is as frustrating as it can be.

2023-12-07 02:56 UTC, dleovl commented
VitaSDK can be installed on Windows too, but only through WSL, meaning the path of C++ stdlib.h of VitaSDK wouldn't be different (/usr/local/vitasdk/arm-vita-eabi/include/c++/10.3.0/stdlib.h). If you move the folder manually, you can expect errors to occur. The hacky stdlib.h workaround may only break Mac and be fine on a normal install of VitaSDK on Linux and Windows WSL2 if you also edit the SDK itself. Assuming the CMake is fine, this is again out of my hands.